### ISSUE TITLE
I have some problems with the running of the program

### ISSUE THREAD

**Issue by worldso** [BrandonSmithJ/MDN#11]
Recently downloaded and debugged your project, I found that I have some problems in running, what is the input and output of the program and how to make the program work normally，If possible, can you leave your email address to facilitate our communication?

**Comment by worldso** [comment]
AssertionError: No datasets found for ['chl'] within D:\Data\Insitu/*/OLI

**Comment by worldso** [comment]
what meaning this is
	assert(len(data_folder)), f'No datasets found for {products} within {data_path}/*/{sensor}'
	assert(len(data_keys)),  f'No variables found for {products} within {data_path}/*/{sensor}'

**Comment by BrandonSmithJ** [comment]
There is an example in the readme on how to use the program. Inputs are meant to be Rrs, outputs are water quality products (chlorophyll, TSS, etc.). 

The assertion error means you are trying to train a new model using the products interface, which won't work unless you have Rrs/chl data. If you just want a general MDN, look at just using the MDN model and how it is fit within get_estimates.py.

**Comment by worldso** [comment]
> There is an example in the readme on how to use the program. Inputs are meant to be Rrs, outputs are water quality products (chlorophyll, TSS, etc.).
> 
> The assertion error means you are trying to train a new model using the products interface, which won't work unless you have Rrs/chl data. If you just want a general MDN, look at just using the MDN model and how it is fit within get_estimates.py.


I can't understand the meaning of "/*/" in the path "AssertionError: No datasets found for ['chl'] within D:\Data\Insitu/*/OLI", I put the data in "D:\Data\Insitu\ OLI" program still getting the same assert error

**Comment by worldso** [comment]
I am a Chinese university student, and our team is also doing research similar to your team, using deep learning to analyze remote sensing data and then make a judgment on water quality, but I am not very proficient in python, and there are still many questions to be asked. seniors to answer. Thank you very much.

**Comment by BrandonSmithJ** [comment]
There should not be // in your path. I believe you're missing the 'location' folder in your data path, i.e. D:/Data/Insitu/_location_/OLI - where _location_ is meant to signify the name of the dataset. You can have multiple datasets within the Insitu folder, and all of the ones which contain the parameters of interest you are trying to train on (e.g. chl) will be used.
