### ISSUE TITLE
Unable to download weights from repo

### ISSUE THREAD

**Issue by GuiMorin** [BrandonSmithJ/MDN#14]
Dear Brandon,

We have difficulties to download the entire repository, more specifically we can not download the weights of the models because the repo has reached the data quota (c.f. extracts from the log underneath).

I may also have made a mistake somewhere.
But if not, is there any other place where we can download the weights?

I greatly thank you in advance for your help,

Guillaume
  
(extracted from the log generated just now):
""
git-lfs/3.2.0 (GitHub; linux amd64; go 1.18.2)
git version 2.25.1

$ git-lfs filter-process
Error downloading object: Weights/HICO/45313342cb628c8cf45b6e2e29f4dc9a780ee1d403bdb98461e28fcb13ad9ce3.zip (c3b0e04): Smudge error: Error downloading Weights/HICO/45313342cb628c8cf45b6e2e29f4dc9a780ee1d403bdb98461e28fcb13ad9ce3.zip (c3b0e0457ebacd53d842b0541fc60233f70eb75c45b6842333f1918eddc38f07): batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
[...]
""

**Comment by BrandonSmithJ** [comment]
Yes, unfortunately Git LFS only allows downloads of 1 GB / month, which makes it difficult to share the weights through that method. Finding a new way to distribute the weights is on my todo list, but for now I've attached the weights currently in the repo here:

[HICO.zip](https://github.com/BrandonSmithJ/MDN/files/9973033/HICO.zip)
[MSI.zip](https://github.com/BrandonSmithJ/MDN/files/9973031/MSI.zip)
[OLCI.zip](https://github.com/BrandonSmithJ/MDN/files/9973029/OLCI.zip)
[OLI.zip](https://github.com/BrandonSmithJ/MDN/files/9973028/OLI.zip)

All you should need to do is unzip these inside your MDN/Weights/ folder.

**Comment by GuiMorin** [comment]
Brandon.
I greatly thank you .
