### ISSUE TITLE
Unzipping weights - file structure

### ISSUE THREAD

**Issue by NDetenbeck** [BrandonSmithJ/MDN#16]
I also had trouble downloading the weights as noted in the previous posting.  I downloaded these separately from the links in your response.  I unzipped each of these in the Weights folder, and these generated additional zip files.  I unzipped those as well.  In two cases the second zip file unzipped into the base directory while the first created a separate subdirectory, e.g:
[ndetenbe@atmos2 OLI]$ ls
70c22252dff6bc608d1d8e15b1d2d9e62cdaceecf7217f268192964a4c4c1871
70c22252dff6bc608d1d8e15b1d2d9e62cdaceecf7217f268192964a4c4c1871.zip
Round_0
Round_1
Round_2
Round_3
Round_4
Round_5
Round_6
Round_7
Round_8
Round_9
c42180fb52344bc80726538ecdfb07569b29cc802f27ab3c2789ab41302d701e.zip
config

I just want to make sure this structure is correct.  If not, I can generate a subdirectory myself and unzip within it.

**Comment by BrandonSmithJ** [comment]
You don't need to unzip the inner zip files, as the code will do that automatically. So long as you unzipped the sensor zip files into the Weights folder, the code will do the rest.

**Comment by NDetenbeck** [comment]
Thanks for the clarification!

Naomi
