### ISSUE TITLE
setup.py file?

### ISSUE THREAD

**Issue by bziniti** [BrandonSmithJ/MDN#5]
Thank you for making this code available! Your paper about chla retrievals was very interesting and I'm looking forward to understanding the model more. 

Was wondering if you have considered adding a setup.py file for easy use? (related to #2 )

It would make `pip install git+https://github.com/BrandonSmithJ/MDN` possible. 

I used this workaround https://stackoverflow.com/questions/9714635/how-to-install-python-module-without-setup-py/9714750#9714750 but perhaps helpful for future use.

**Comment by BrandonSmithJ** [comment]
You're welcome! 

Yes that is one potential option in addition to pypi. Unfortunately, getting the module available there has taken a backseat while I've been working to get things upgraded to TF2.x, which requires some major rewrites. Once that's ready, it will be released on PyPi at the same time to allow easy pip installs. 

In the meantime though, I'll look into just adding a quick setup file. Thanks for the suggestion!

**Comment by BrandonSmithJ** [comment]
I've now added support for `pip install git+https://github.com/BrandonSmithJ/MDN` - let me know if you run into any issues!

**Comment by bziniti** [comment]
@BrandonSmithJ Thank you so much! This is great!
