### ISSUE TITLE
Training MDN model

### ISSUE THREAD

**Issue by geo-dingky** [BrandonSmithJ/MDN#6]
Hello, how should I train the MDN model with my own data set ?

**Comment by BrandonSmithJ** [comment]
Assuming your dataset consists of Rrs and the respective band centers, you would just need something like this:

```
from MDN.parameters import get_args
from MDN.product_estimation import get_estimates
import numpy as np 

sensor = 'YOUR_SENSOR'
data   = {
  'x_train' : YOUR_X_TRAIN, # shaped [n_samples, n_bands]
  'y_train' : YOUR_Y_TRAIN, # shaped [n_samples, n_outputs]
  'x_test'  : YOUR_X_TEST, # shaped [n_samples, n_bands]
  'y_test'  : YOUR_Y_TEST, # shaped [n_samples, n_outputs]
}

args = get_args(sensor=sensor)
estimates, slices = get_estimates(args, **data)
estimates = np.median(estimates, 0) # median over the n_rounds
```

If you're using a sensor which is undefined or with a different set of wavelengths, define it within meta.py. The same will likely work if you're using just a random dataset and not Rrs / wavelengths, but you'll need to define a custom 'sensor' in meta.py and give indices as the bands.

Alternatively, you can use the MDN class directly in the same manner as the sklearn api.

**Comment by geo-dingky** [comment]
thanks,
I try to get the following error

![image](https://user-images.githubusercontent.com/75166335/143238817-48a0d989-f153-4839-913a-b33b5c908f70.png)
Can you tell me what to do

**Comment by BrandonSmithJ** [comment]
Sorry for the delay getting back to you. When using a notebook to run the code, you need to pass in the keyword argument 'use_cmdline=False' to the get_args function. Running via a script will avoid this issue as well.
