### ISSUE TITLE
 'generate_estimates' function lost

### ISSUE THREAD

**Issue by bodhifan** [BrandonSmithJ/MDN#8]
Hi Brandon, I am using your code to train my data, and I can't find 'generate_estimates' function in 'product_estimation.py' file. could you fix this issue? thx.

**Comment by BrandonSmithJ** [comment]
generate_estimates is a catch-all helper that I have written for various purposes, rather than as a public function. If you're trying to just run benchmarking code (which is where generate_estimates is used in product_estimation.py), the following function should be equivalent:

```
def generate_estimates(args, bands, x_train, y_train, x_test, y_test, slices, locs=None):
    estimates, slices = get_estimates(args, x_train, y_train, x_test, y_test, slices)
    estimates = np.median(estimates, 0)
    benchmarks = run_benchmarks(args.sensor, x_test, y_test, x_train, y_train, slices, args)
    for p in slices: 
        if p not in benchmarks: benchmarks[p] = {}
        benchmarks[p].update({'MDN' : estimates[..., slices[p]]})
    return benchmarks
```
